{% set name = 'bitops' %}
{% set version = '1.0-6' %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-{{ name|lower }}_{{ version }}.tar.gz"
  sha256: "9b731397b7166dd54941fb0d2eac6df60c7a483b2e790f7eb15b4d7b79c9d69c"

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

requirements:
  build:
    - r-base {{ r_base }}
    - {{ compiler('c') }}

  run:
    - r-base

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: https://CRAN.R-project.org/package=bitops
  license: GPLv2
  summary: "R functions for bitwise operations on integer vectors."


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Package: bitops
# Version: 1.0-6
# Date: 2013-08-17
# Author: S original by Steve Dutky <sdutky@terpalum.umd.edu> initial R port and extensions by Martin Maechler; revised and modified by Steve Dutky
# Maintainer: Martin Maechler <maechler@stat.math.ethz.ch>
# Title: Bitwise Operations
# Description: Functions for bitwise operations on integer vectors.
# License: GPL (>= 2)
# Packaged: 2013-08-17 15:58:57 UTC; maechler
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2013-08-17 21:10:34
#----------------------------------------------------------------------
