#!/bin/bash

basedir=$(cd "`dirname ${BASH_SOURCE[0]}`" && pwd)

HOST_ARCH=`uname -m`

shell=0
img=
build_pkgs=
build_opts=
make_jobs=
FEATURE_OPT=0

use_pkg_cache=1

# Default versions for various scripting language runtimes and libraries.
# Generally, these should match the latest versions available (or soon to be
# available) in BioBuilds. Used below with the corresponding "conda build"
# options to reduce build headaches (since the "conda build" defaults don't
# always match the defaults we want for BioBuilds).
NUMPY_VER="1.12"
PERL_VER="5.22.0"
PYTHON_VER="2.7"
R_VER="3.3.2"

# Always allocate a pseudo-TTY in (-t) and attach STDIN to (-i) the container;
# if we don't, conda build messages (particularly in the test phase) can
# disappear into the void, which making debugging recipes difficult.
docker_opts="-t -i"

abort() {
    msg=${1:-"Unknown error"}
    echo "ERROR: $msg" >&2
    exit 1
}

if [[ -z "$BB_BUILD_IMAGE" ]]; then
    case "$HOST_ARCH" in
        x86_64)  img="biobuilds/build-x86_64" ;;
        ppc64le) img="biobuilds/build-ppc64le" ;;
        *) abort 'No default build image for this architecture' ;;
    esac
else
    img="${BB_BUILD_IMAGE}"
fi

# Process command line arguments
while [ "$1" != "" ]; do
    case "$1" in
        "--img")
            shift; img="$1"
            ;;
        "--img="*)
            img="${1#*=}"
            ;;
        "--src" | "--source")
            shift; basedir="$1"
            ;;
        "--src="* | "--source="*)
            basedir="${1#*=}"
            ;;
        "--shell")
            shell=1
            ;;
        "-j" | "--jobs")
            shift; make_jobs="$1"
            ;;
        "-j"*)
            make_jobs="${1:2}"
            ;;
        "--jobs="*)
            make_jobs="${1#*=}"
            [[ -z "$make_jobs" ]] && abort "'--jobs' must have non-empty value"
            ;;
        "--no-pkg-cache")
            use_pkg_cache=0
            ;;
        "-o" | "--opt")
            FEATURE_OPT=1
            ;;
        "--psxe")
            shift; psxe_root="$1"
            ;;
        "--psxe="*)
            psxe_root="${1#*=}"
            ;;
        "--numpy")
            shift; NUMPY_VER="$1"
            ;;
        "--perl")
            shift; PERL_VER="$1"
            ;;
        "--python")
            shift; PYTHON_VER="$1"
            ;;
        "--R")
            shift; R_VER="$1"
            ;;
        "-c" | "--channel")
            shift; build_opts="$build_opts --channel $1"
            ;;
        "-"*)
            build_opts="$build_opts $1"
            ;;
        *)
            build_pkgs="$build_pkgs $1"
            ;;
    esac
    shift
done

# Always tell "conda build" what versions of various languages and libraries to
# use. When coupled with the defaults above, helps ensure the packages we build
# correctly target the latest BioBuilds release.
build_opts="$build_opts --numpy ${NUMPY_VER}"
build_opts="$build_opts --perl ${PERL_VER}"
build_opts="$build_opts --python ${PYTHON_VER}"
build_opts="$build_opts --R ${R_VER}"


# Mount the host's Intel Parallel Studio XE install directory as a volume in
# the build container. This simplifies license management and allows us to use
# the "standard" (i.e., publicly-distributed) x86_64 build image for building
# "linux-64" packages with the "opt" feature enabled. (The alternative would be
# to install Parallel Studio inside a Docker image, but that approach would
# make the image [1] several gigabytes larger and [2] not re-distributable due
# to license management issues.)
if [[ "$HOST_ARCH" == 'x86_64' && "$FEATURE_OPT" -eq 1 ]]; then
    # Standard install location if the "--psxe" argument was not provided
    : ${psxe_root:=/opt/intel}

    # Make sure there's at least something resembling a Parallel Studio install
    # in the directory
    test -e "${psxe_root}/bin/compilervars.sh" || \
        abort "No Intel Parallel Studio installation found in '$psxe_root'!"

    docker_opts="$docker_opts -v ${psxe_root}:/opt/intel:ro"
    docker_opts="$docker_opts -e PSXE_ROOT=/opt/intel"
fi


# Check for cache directory containing packages from "defaults" and other
# channels that may be needed for the build process. This saves us the trouble
# of having to repeatedly download packages when using the build container.
PKG_CACHE_BASE="conda-bld/pkg_cache"
if [ "$HOST_ARCH" == 'x86_64' ]; then
    PKG_CACHE_DIR="${basedir}/${PKG_CACHE_BASE}/linux-64"
elif [ "$HOST_ARCH" == 'ppc64le' ]; then
    PKG_CACHE_DIR="${basedir}/${PKG_CACHE_BASE}/linux-ppc64le"
fi
if [[ "$use_pkg_cache" -eq 1 && \
        -f "${PKG_CACHE_DIR}/.index.json" && \
        -f "${PKG_CACHE_DIR}/repodata.json" ]]; then
    build_opts="$build_opts -c file:///src/${PKG_CACHE_BASE}"
fi

# Sanity check arguments
if [[ ! -z "$make_jobs" ]]; then
    [[ "$make_jobs" -gt 0 ]] || \
        abort "value for '-j'/'--jobs' must be integer > 0"
    BB_MAKE_JOBS=${make_jobs}
fi
if [ $shell -eq 0 ]; then
    [ "x$build_pkgs" == "x" ] && \
        abort "must specify at least one package to build!"
    for pkg in $build_pkgs; do
        [ -f "${basedir}/${pkg}/meta.yaml" ] || \
            abort "No conda recipe found in '${basedir}/${pkg}'!"
    done
else
    build_opts="--shell"
    build_pkgs=
fi

#------------------------------------------------------------------------------
# Launch the build container.
#
# - Set the MAKE_JOBS environment variable so users can control the number of
#   CPUs used when building recipes that use the "biobuilds-build" package to
#   configure their build environment.
#
# - Pass the $BB_* environment variables to provide some level of backwards
#   compatibility with legacy recipes that do not configure their build
#   environment using the "biobuilds-build" package. Note that as of the
#   2017.05 release, the build container's ENTRYPOINT script no longer sources
#   "bb-build-flags.env"; to rebuild older recipes using the standard set of
#   build flags, you will have to do one of the following:
#
#     - "Manually" set and export $BB_ARCH_FLAGS and $BB_OPT_FLAGS;
#     - Source the environment script _before_ running "docker-build"; or
#     - Build using an older (pre-2017.05) image using either the "--img"
#       option or the $BB_BUILD_IMAGE environment variable.
#
#------------------------------------------------------------------------------
echo "Launching image '$img'..." >&2
docker run --rm \
    -e MAKE_JOBS=${make_jobs} \
    -e FEATURE_OPT=${FEATURE_OPT} \
    -e BB_MAKE_JOBS=${BB_MAKE_JOBS:-1} \
    -e BB_ARCH_FLAGS="${BB_ARCH_FLAGS:-}" \
    -e BB_OPT_FLAGS="${BB_OPT_FLAGS:-}" \
    -v "${basedir}:/src" \
    $docker_opts \
    "$img" $build_opts $build_pkgs
