package:
  name: trimmomatic
  version: "0.36"

source:
  fn: "trimmomatic-0.36.zip"
  url:
    - "http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/Trimmomatic-0.36.zip"
    - "http://download.lab7.io/sources/trimmomatic-0.36.zip"
  md5: "8549130d86b6f0382b1a71a2eb45de39"

build:
  number: 0

test:
  commands:
    - trimmomatic -version
    # Check to see if JRE arguments are being properly handled
    - trimmomatic -Xmx256m -version

about:
  home: "http://www.usadellab.org/cms/?page=trimmomatic"
  license: GPLv3
  license_file: LICENSE
  summary: "Flexible read trimming tool for Illumina NGS data"
