{% set name = "mime" %}
{% set version = "0.5" %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-{{ name|lower }}_{{ version }}.tar.gz"
  sha256: "fcc72115afb0eb43237da872754464f37ae9ae097f332ec7984149b5e3a82145"

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base {{ r_base }}
    - {{ compiler('c') }}

  run:
    - r-base

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: https://github.com/yihui/mime
  license: GPL
  summary: Map filenames to mime types
  description: |
    Guesses the MIME type from a filename extension using the data derived from
    /etc/mime.types in UNIX-type systems.


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Package: mime
# Type: Package
# Title: Map Filenames to MIME Types
# Version: 0.5
# Date: 2016-07-07
# Authors@R: c(person("Jeffrey", "Horner", role = "ctb"), person("Yihui", "Xie", role = c("aut", "cre"), email = "xie@yihui.name"))
# Maintainer: Yihui Xie <xie@yihui.name>
# Description: Guesses the MIME type from a filename extension using the data derived from /etc/mime.types in UNIX-type systems.
# Imports: tools
# License: GPL
# URL: https://github.com/yihui/mime
# BugReports: https://github.com/yihui/mime/issues
# LazyData: TRUE
# RoxygenNote: 5.0.1
# NeedsCompilation: yes
# Packaged: 2016-07-07 04:44:41 UTC; yihui
# Author: Jeffrey Horner [ctb], Yihui Xie [aut, cre]
# Repository: CRAN
# Date/Publication: 2016-07-07 07:38:00
#----------------------------------------------------------------------
