--- Makefile
+++ Makefile
@@ -36,12 +36,14 @@ AOBJS=      bam_index.o bam_plcmd.o sam_view.o \
             cut_target.o phase.o bam2depth.o padding.o bedcov.o bamshuf.o \
             faidx.o stats.o stats_isize.o bam_flags.o bam_split.o \
             bam_tview.o bam_tview_curses.o bam_tview_html.o bam_lpileup.o
-INCLUDES=   -I. -I$(HTSDIR)
+INCLUDES=   -I. -I$(HTSDIR)/include
 LIBCURSES=  -lcurses # -lXCurses
 
 prefix      = /usr/local
 exec_prefix = $(prefix)
 bindir      = $(exec_prefix)/bin
+libdir      = $(prefix)/lib
+incdir      = $(prefix)/include/samtools
 mandir      = $(prefix)/share/man
 man1dir     = $(mandir)/man1
 
@@ -82,10 +84,9 @@ all: $(PROGRAMS) $(BUILT_MISC_PROGRAMS) $(BUILT_TEST_PROGRAMS)
 
 
 # Adjust $(HTSDIR) to point to your top-level htslib directory
-HTSDIR = ../htslib
-include $(HTSDIR)/htslib.mk
-HTSLIB = $(HTSDIR)/libhts.a
-BGZIP  = $(HTSDIR)/bgzip
+HTSDIR =
+HTSLIB = $(HTSDIR)/lib/libhts.a
+BGZIP  = $(HTSDIR)/bin/bgzip
 
 
 PACKAGE_VERSION = 1.2
@@ -128,49 +129,49 @@ bam_h = bam.h $(htslib_bgzf_h) $(htslib_sam_h)
 bam2bcf_h = bam2bcf.h $(htslib_vcf_h) errmod.h
 bam_lpileup_h = bam_lpileup.h $(htslib_sam_h)
 bam_plbuf_h = bam_plbuf.h $(htslib_sam_h)
-bam_tview_h = bam_tview.h $(htslib_hts_h) $(htslib_sam_h) $(htslib_faidx_h) $(bam2bcf_h) $(HTSDIR)/htslib/khash.h $(bam_lpileup_h)
+bam_tview_h = bam_tview.h $(htslib_hts_h) $(htslib_sam_h) $(htslib_faidx_h) $(bam2bcf_h) $(HTSDIR)/include/htslib/khash.h $(bam_lpileup_h)
 sam_h = sam.h $(htslib_sam_h) $(bam_h)
-sample_h = sample.h $(HTSDIR)/htslib/kstring.h
+sample_h = sample.h $(HTSDIR)/include/htslib/kstring.h
 
 bam.o: bam.c $(bam_h) sam_header.h
-bam2bcf.o: bam2bcf.c $(htslib_sam_h) $(HTSDIR)/htslib/kstring.h $(HTSDIR)/htslib/kfunc.h $(bam2bcf_h) errmod.h
-bam2bcf_indel.o: bam2bcf_indel.c $(htslib_sam_h) $(bam2bcf_h) kprobaln.h $(HTSDIR)/htslib/khash.h $(HTSDIR)/htslib/ksort.h
+bam2bcf.o: bam2bcf.c $(htslib_sam_h) $(HTSDIR)/include/htslib/kstring.h $(HTSDIR)/include/htslib/kfunc.h $(bam2bcf_h) errmod.h
+bam2bcf_indel.o: bam2bcf_indel.c $(htslib_sam_h) $(bam2bcf_h) kprobaln.h $(HTSDIR)/include/htslib/khash.h $(HTSDIR)/include/htslib/ksort.h
 bam2depth.o: bam2depth.c $(htslib_sam_h) samtools.h
 bam_aux.o: bam_aux.c
 bam_cat.o: bam_cat.c $(htslib_bgzf_h) $(bam_h)
 bam_color.o: bam_color.c $(bam_h)
-bam_import.o: bam_import.c $(HTSDIR)/htslib/kstring.h $(bam_h) $(HTSDIR)/htslib/kseq.h
-bam_index.o: bam_index.c $(htslib_hts_h) $(htslib_sam_h) $(HTSDIR)/htslib/khash.h
-bam_lpileup.o: bam_lpileup.c $(bam_plbuf_h) $(bam_lpileup_h) $(HTSDIR)/htslib/ksort.h
+bam_import.o: bam_import.c $(HTSDIR)/include/htslib/kstring.h $(bam_h) $(HTSDIR)/include/htslib/kseq.h
+bam_index.o: bam_index.c $(htslib_hts_h) $(htslib_sam_h) $(HTSDIR)/include/htslib/khash.h
+bam_lpileup.o: bam_lpileup.c $(bam_plbuf_h) $(bam_lpileup_h) $(HTSDIR)/include/htslib/ksort.h
 bam_mate.o: bam_mate.c $(bam_h)
 bam_md.o: bam_md.c $(htslib_faidx_h) $(sam_h) kprobaln.h
 bam_pileup.o: bam_pileup.c $(sam_h)
 bam_plbuf.o: bam_plbuf.c $(htslib_hts_h) $(htslib_sam_h) $(bam_plbuf_h)
-bam_plcmd.o: bam_plcmd.c $(htslib_sam_h) $(htslib_faidx_h) $(HTSDIR)/htslib/kstring.h $(HTSDIR)/htslib/khash_str2int.h sam_header.h samtools.h $(bam2bcf_h) $(sample_h)
+bam_plcmd.o: bam_plcmd.c $(htslib_sam_h) $(htslib_faidx_h) $(HTSDIR)/include/htslib/kstring.h $(HTSDIR)/include/htslib/khash_str2int.h sam_header.h samtools.h $(bam2bcf_h) $(sample_h)
 bam_reheader.o: bam_reheader.c $(htslib_bgzf_h) $(bam_h)
-bam_rmdup.o: bam_rmdup.c $(sam_h) $(HTSDIR)/htslib/khash.h
-bam_rmdupse.o: bam_rmdupse.c $(sam_h) $(HTSDIR)/htslib/khash.h $(HTSDIR)/htslib/klist.h
-bam_sort.o: bam_sort.c $(HTSDIR)/htslib/ksort.h $(HTSDIR)/htslib/khash.h $(HTSDIR)/htslib/klist.h $(HTSDIR)/htslib/kstring.h $(htslib_sam_h)
+bam_rmdup.o: bam_rmdup.c $(sam_h) $(HTSDIR)/include/htslib/khash.h
+bam_rmdupse.o: bam_rmdupse.c $(sam_h) $(HTSDIR)/include/htslib/khash.h $(HTSDIR)/include/htslib/klist.h
+bam_sort.o: bam_sort.c $(HTSDIR)/include/htslib/ksort.h $(HTSDIR)/include/htslib/khash.h $(HTSDIR)/include/htslib/klist.h $(HTSDIR)/include/htslib/kstring.h $(htslib_sam_h)
 bam_stat.o: bam_stat.c $(bam_h) samtools.h
 bam_tview.o: bam_tview.c $(bam_tview_h) $(htslib_faidx_h) $(htslib_sam_h) $(htslib_bgzf_h)
 bam_tview_curses.o: bam_tview_curses.c $(bam_tview_h)
 bam_tview_html.o: bam_tview_html.c $(bam_tview_h)
 bam_flags.o: bam_flags.c $(sam_h)
-bamshuf.o: bamshuf.c $(htslib_sam_h) $(HTSDIR)/htslib/ksort.h samtools.h
+bamshuf.o: bamshuf.c $(htslib_sam_h) $(HTSDIR)/include/htslib/ksort.h samtools.h
 bamtk.o: bamtk.c $(htslib_hts_h) version.h samtools.h
-bedcov.o: bedcov.c $(HTSDIR)/htslib/kstring.h $(htslib_sam_h) $(HTSDIR)/htslib/kseq.h
-bedidx.o: bedidx.c $(HTSDIR)/htslib/ksort.h $(HTSDIR)/htslib/kseq.h $(HTSDIR)/htslib/khash.h
+bedcov.o: bedcov.c $(HTSDIR)/include/htslib/kstring.h $(htslib_sam_h) $(HTSDIR)/include/htslib/kseq.h
+bedidx.o: bedidx.c $(HTSDIR)/include/htslib/ksort.h $(HTSDIR)/include/htslib/kseq.h $(HTSDIR)/include/htslib/khash.h
 cut_target.o: cut_target.c $(bam_h) errmod.h $(htslib_faidx_h)
-errmod.o: errmod.c errmod.h $(HTSDIR)/htslib/ksort.h
+errmod.o: errmod.c errmod.h $(HTSDIR)/include/htslib/ksort.h
 kprobaln.o: kprobaln.c kprobaln.h
 padding.o: padding.c sam_header.h $(sam_h) $(bam_h) $(htslib_faidx_h)
-phase.o: phase.c $(htslib_sam_h) errmod.h $(HTSDIR)/htslib/kseq.h $(HTSDIR)/htslib/khash.h $(HTSDIR)/htslib/ksort.h
+phase.o: phase.c $(htslib_sam_h) errmod.h $(HTSDIR)/include/htslib/kseq.h $(HTSDIR)/include/htslib/khash.h $(HTSDIR)/include/htslib/ksort.h
 sam.o: sam.c $(htslib_faidx_h) $(sam_h)
-sam_header.o: sam_header.c sam_header.h $(HTSDIR)/htslib/khash.h
-sam_view.o: sam_view.c $(htslib_sam_h) $(htslib_faidx_h) $(HTSDIR)/htslib/kstring.h $(HTSDIR)/htslib/khash.h samtools.h
-sample.o: sample.c $(sample_h) $(HTSDIR)/htslib/khash.h
-stats_isize.o: stats_isize.c stats_isize.h $(HTSDIR)/htslib/khash.h
-stats.o: stats.c $(sam_h) sam_header.h samtools.h stats_isize.h $(HTSDIR)/htslib/khash.h $(HTSDIR)/htslib/khash_str2int.h $(htslib_faidx_h)
+sam_header.o: sam_header.c sam_header.h $(HTSDIR)/include/htslib/khash.h
+sam_view.o: sam_view.c $(htslib_sam_h) $(htslib_faidx_h) $(HTSDIR)/include/htslib/kstring.h $(HTSDIR)/include/htslib/khash.h samtools.h
+sample.o: sample.c $(sample_h) $(HTSDIR)/include/htslib/khash.h
+stats_isize.o: stats_isize.c stats_isize.h $(HTSDIR)/include/htslib/khash.h
+stats.o: stats.c $(sam_h) sam_header.h samtools.h stats_isize.h $(HTSDIR)/include/htslib/khash.h $(HTSDIR)/include/htslib/khash_str2int.h $(htslib_faidx_h)
 
 
 # test programs
@@ -252,10 +253,10 @@ misc/md5sum-lite: misc/md5sum-lite.o
 misc/wgsim: misc/wgsim.o
 	$(CC) $(LDFLAGS) -o $@ misc/wgsim.o $(LDLIBS) -lm -lz
 
-misc/ace2sam.o: misc/ace2sam.c $(HTSDIR)/htslib/kstring.h $(HTSDIR)/htslib/kseq.h
+misc/ace2sam.o: misc/ace2sam.c $(HTSDIR)/include/htslib/kstring.h $(HTSDIR)/include/htslib/kseq.h
 misc/md5.o: misc/md5.c misc/md5.h
-misc/md5fa.o: misc/md5fa.c misc/md5.h $(HTSDIR)/htslib/kseq.h
-misc/wgsim.o: misc/wgsim.c $(HTSDIR)/htslib/kseq.h
+misc/md5fa.o: misc/md5fa.c misc/md5.h $(HTSDIR)/include/htslib/kseq.h
+misc/wgsim.o: misc/wgsim.c $(HTSDIR)/include/htslib/kseq.h
 
 misc/maq2sam-short.o: misc/maq2sam.c
 	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ misc/maq2sam.c
@@ -268,9 +269,11 @@ misc/md5sum-lite.o: misc/md5.c misc/md5.h
 
 
 install: $(PROGRAMS) $(BUILT_MISC_PROGRAMS)
-	$(INSTALL_DIR) $(DESTDIR)$(bindir) $(DESTDIR)$(man1dir)
-	$(INSTALL_PROGRAM) $(PROGRAMS) $(MISC_PROGRAMS) $(DESTDIR)$(bindir)
-	$(INSTALL_DATA) samtools.1 $(DESTDIR)$(man1dir)
+	$(INSTALL_DIR) $(bindir) $(man1dir) $(libdir) $(incdir)
+	$(INSTALL_PROGRAM) $(PROGRAMS) $(MISC_PROGRAMS) $(bindir)
+	$(INSTALL_DATA) samtools.1 $(man1dir)
+	$(INSTALL_DATA) libbam.a $(libdir)
+	$(INSTALL_DATA) version.h sam.h bam.h $(incdir)
 
 
 testclean:
