{% set name = "gtools" %}
{% set version = "3.5.0" %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-{{ name|lower }}_{{ version }}.tar.gz"
  sha256: "86b6a51a92ddb3c78095e0c5dc20414c67f6e28f915bf0ee11406adad3e476f6"

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

requirements:
  build:
    - r-base {{ r_base }}
    - {{ compiler('c') }}

  run:
    - r-base

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: https://CRAN.R-project.org/package=gtools
  license: GPLv2
  summary: 'Various functions to assist in R programming'


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Package: gtools
# Title: Various R Programming Tools
# Description: Functions to assist in R programming, including: - assist in developing, updating, and maintaining R and R packages ('ask', 'checkRVersion', 'getDependencies', 'keywords', 'scat'), - calculate the logit and inverse logit transformations ('logit', 'inv.logit'), - test if a value is missing, empty or contains only NA and NULL values ('invalid'), - manipulate R's .Last function ('addLast'), - define macros ('defmacro'), - detect odd and even integers ('odd', 'even'), - convert strings containing non-ASCII characters (like single quotes) to plain ASCII ('ASCIIfy'), - perform a binary search ('binsearch'), - sort strings containing both numeric and character components ('mixedsort'), - create a factor variable from the quantiles of a continuous variable ('quantcut'), - enumerate permutations and combinations ('combinations', 'permutation'), - calculate and convert between fold-change and log-ratio ('foldchange', 'logratio2foldchange', 'foldchange2logratio'), - calculate probabilities and generate random numbers from Dirichlet distributions ('rdirichlet', 'ddirichlet'), - apply a function over adjacent subsets of a vector ('running'), - modify the TCP\_NODELAY ('de-Nagle') flag for socket objects, - efficient 'rbind' of data frames, even if the column names don't match ('smartbind'), - generate significance stars from p-values ('stars.pval'), - convert characters to/from ASCII codes.
# Version: 3.5.0
# Date: 2015-05-26
# Author: Gregory R. Warnes, Ben Bolker, and Thomas Lumley
# Maintainer: Gregory R. Warnes <greg@warnes.net>
# License: GPL-2
# Repository: CRAN
# Repository/R-Forge/Project: r-gregmisc
# Repository/R-Forge/Revision: 2048
# Repository/R-Forge/DateTimeStamp: 2015-05-27 16:38:37
# Date/Publication: 2015-05-29 10:36:40
# NeedsCompilation: yes
# Packaged: 2015-05-27 16:45:10 UTC; rforge
# Depends: R (>= 2.10)
#----------------------------------------------------------------------
