{% set name = "gdata" %}
{% set version = "2.18.0" %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-{{ name|lower }}_{{ version }}.tar.gz"
  sha256: "4b287f59f5bbf5fcbf18db16477852faac4a605b10c5284c46b93fa6e9918d7f"

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RUnit
requirements:
  build:
    - r-base {{ r_base }}
    - r-gtools

  run:
    - r-base
    - r-gtools

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: https://CRAN.R-project.org/package=gdata
  license: GPL-2
  summary: Various R programming tools for data manipulation


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Package: gdata
# Title: Various R Programming Tools for Data Manipulation
# Description: Various R programming tools for data manipulation, including: - medical unit conversions ('ConvertMedUnits', 'MedUnits'), - combining objects ('bindData', 'cbindX', 'combine', 'interleave'), - character vector operations ('centerText', 'startsWith', 'trim'), - factor manipulation ('levels', 'reorder.factor', 'mapLevels'), - obtaining information about R objects ('object.size', 'elem', 'env', 'humanReadable', 'is.what', 'll', 'keep', 'ls.funs', 'Args','nPairs', 'nobs'), - manipulating MS-Excel formatted files ('read.xls', 'installXLSXsupport', 'sheetCount', 'xlsFormats'), - generating fixed-width format files ('write.fwf'), - extricating components of date & time objects ('getYear', 'getMonth', 'getDay', 'getHour', 'getMin', 'getSec'), - operations on columns of data frames  ('matchcols', 'rename.vars'), - matrix operations ('unmatrix', 'upperTriangle', 'lowerTriangle'), - operations on vectors ('case', 'unknownToNA', 'duplicated2', 'trimSum'), - operations on data frames ('frameApply', 'wideByFactor'), - value of last evaluated expression ('ans'), and - wrapper for 'sample' that ensures consistent behavior for both scalar and vector arguments ('resample').
# Depends: R (>= 2.3.0)
# SystemRequirements: perl (>= 5.10.0)
# Imports: gtools, stats, methods, utils
# Version: 2.18.0
# Date: 2017-06-05
# Author: Gregory R. Warnes, Ben Bolker, Gregor Gorjanc, Gabor Grothendieck, Ales Korosec, Thomas Lumley, Don MacQueen, Arni Magnusson, Jim Rogers, and others
# Maintainer: Gregory R. Warnes <greg@warnes.net>
# License: GPL-2
# NeedsCompilation: no
# Suggests: RUnit
# Packaged: 2017-06-05 21:27:42 UTC; gwarnes
# Repository: CRAN
# Date/Publication: 2017-06-06 15:34:19 UTC
#----------------------------------------------------------------------
