--- Makefile
+++ Makefile
@@ -1,16 +1,20 @@
 DEBUG ?= 0
 PARALLEL ?= 0
 STATIC ?= 0
+PREFIX ?= /usr/local
 
 # Submodules
 PWD = $(shell pwd)
 SEQTK_ROOT ?= ${PWD}/src/htslib/
 BOOST_ROOT ?= ${PWD}/src/modular-boost
 
+# Linker option for libhts, which can be overriden from the make command line
+LIBHTS = -lhts
+
 # Flags
 CXX=g++
-CXXFLAGS += -isystem ${SEQTK_ROOT} -isystem ${BOOST_ROOT} -pedantic -W -Wall -Wno-unknown-pragmas -D__STDC_LIMIT_MACROS -fno-strict-aliasing
-LDFLAGS += -L${SEQTK_ROOT} -L${BOOST_ROOT}/stage/lib -lboost_iostreams -lboost_filesystem -lboost_system -lboost_program_options -lboost_date_time 
+CXXFLAGS += -pedantic -W -Wall -Wno-unknown-pragmas -D__STDC_LIMIT_MACROS -fno-strict-aliasing
+LDFLAGS += -lboost_iostreams -lboost_filesystem -lboost_system -lboost_program_options -lboost_date_time
 
 # Additional flags for release/debug
 ifeq (${PARALLEL}, 1)
@@ -21,9 +25,9 @@
 
 # Additional flags for release/debug
 ifeq (${STATIC}, 1)
-	LDFLAGS += -static -static-libgcc -pthread -lhts -lz
+	LDFLAGS += -static -static-libgcc -pthread $(LIBHTS) -lz
 else
-	LDFLAGS += -lhts -lz -Wl,-rpath,${SEQTK_ROOT},-rpath,${BOOST_ROOT}/stage/lib
+	LDFLAGS += $(LIBHTS) -lz
 endif
 ifeq (${DEBUG}, 1)
 	CXXFLAGS += -g -O0 -fno-inline -DDEBUG
@@ -41,29 +45,22 @@
 DELLYSOURCES = $(wildcard src/*.h) $(wildcard src/*.cpp)
 
 # Targets
-TARGETS = .htslib .bcftools .boost src/delly src/cov src/dpe
+TARGETS = src/delly src/delly-cov src/delly-dpe
 
 all:   	$(TARGETS)
 
-.htslib: $(HTSLIBSOURCES)
-	cd src/htslib && make && make lib-static && cd ../../ && touch .htslib
-
-.bcftools: $(HTSLIBSOURCES)
-	cd src/bcftools && make && cd ../../ && touch .bcftools
-
-.boost: $(BOOSTSOURCES)
-	cd src/modular-boost && ./bootstrap.sh --prefix=${PWD}/src/modular-boost --without-icu --with-libraries=iostreams,filesystem,system,program_options,date_time && ./b2 && ./b2 headers && cd ../../ && touch .boost
+src/delly: $(DELLYSOURCES)
+	$(CXX) $(CXXFLAGS) $(subst delly-,,$@).cpp -o $@ $(LDFLAGS)
 
-src/delly: .htslib .bcftools .boost $(DELLYSOURCES)
-	$(CXX) $(CXXFLAGS) $@.cpp -o $@ $(LDFLAGS)
+src/delly-cov: $(DELLYSOURCES)
+	$(CXX) $(CXXFLAGS) $(subst delly-,,$@).cpp -o $@ $(LDFLAGS)
 
-src/cov: .htslib .bcftools .boost $(DELLYSOURCES)
-	$(CXX) $(CXXFLAGS) $@.cpp -o $@ $(LDFLAGS)
-
-src/dpe: .htslib .bcftools .boost $(DELLYSOURCES)
-	$(CXX) $(CXXFLAGS) $@.cpp -o $@ $(LDFLAGS)
+src/delly-dpe: $(DELLYSOURCES)
+	$(CXX) $(CXXFLAGS) $(subst delly-,,$@).cpp -o $@ $(LDFLAGS)
 
 clean:
-	cd src/htslib && make clean
-	cd src/modular-boost && ./b2 --clean-all
 	rm -f $(TARGETS) $(TARGETS:=.o) .htslib .boost .bcftools
+
+install: $(TARGETS)
+	install -m 755 -d $(PREFIX)/bin
+	install -m 755 $(TARGETS) $(PREFIX)/bin
