package:
  name: mock
  version: 1.0.1

source:
  fn: mock-1.0.1.tar.gz
  url: https://pypi.python.org/packages/source/m/mock/mock-1.0.1.tar.gz
  md5: c3971991738caa55ec7c356bbc154ee2

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - mock

about:
  home: http://www.voidspace.org.uk/python/mock/
  license: BSD
  license_file: LICENSE.txt
