package:
  name: r-dplyr
  version: "0.4.3"

source:
  fn: dplyr_0.4.3.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/dplyr_0.4.3.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/dplyr/dplyr_0.4.3.tar.gz
  md5: "19d4ee8b0a196073c390fa6ecb73eb11"

build:
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r
    - gcc     # [not win and not ppc64le]
    - r-bh >=1.58.0_1
    - r-dbi >=0.3
    - r-r6
    - r-rcpp
    - r-assertthat
    - r-lazyeval >=0.1.10
    - r-magrittr

  run:
    - r
    - libgcc  # [not win and not ppc64le]
    - r-dbi >=0.3
    - r-r6
    - r-rcpp
    - r-assertthat
    - r-lazyeval >=0.1.10
    - r-magrittr

test:
  commands:
    - $R -e "library('dplyr')" # [not win]
    - "\"%R%\" -e \"library('dplyr')\"" # [win]

about:
  home: 'https://github.com/hadley/dplyr'
  license: MIT
  license_file: LICENSE
  summary: 'Fast, consistent tool for working with dataframe-like objects, both in and out of memory'


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:

# Package: dplyr
# Type: Package
# Version: 0.4.3
# Title: A Grammar of Data Manipulation
# Description: A fast, consistent tool for working with data frame like objects, both in memory and out of memory.
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", c("aut", "cre")), person("Romain", "Francois", , "romain@r-enthusiasts.com", role = "aut"), person("RStudio", role = "cph") )
# URL: https://github.com/hadley/dplyr
# BugReports: https://github.com/hadley/dplyr/issues
# Depends: R (>= 3.1.2)
# Imports: assertthat, utils, R6, Rcpp, magrittr, lazyeval (>= 0.1.10), DBI (>= 0.3)
# Suggests: RSQLite (>= 1.0.0), RMySQL, RPostgreSQL, data.table, testthat, knitr, microbenchmark, ggplot2, mgcv, Lahman (>= 3.0-1), nycflights13, methods
# VignetteBuilder: knitr
# LazyData: yes
# LinkingTo: Rcpp (>= 0.12.0), BH (>= 1.58.0-1)
# License: MIT + file LICENSE
# Collate: 'RcppExports.R' 'all-equal.r' 'bench-compare.r' 'chain.r' 'cluster.R' 'colwise.R' 'compute-collect.r' 'copy-to.r' 'data-lahman.r' 'data-nasa.r' 'data-nycflights13.r' 'data-temp.r' 'data.r' 'dataframe.R' 'dbi-s3.r' 'desc.r' 'distinct.R' 'do.r' 'dplyr.r' 'explain.r' 'failwith.r' 'frame-data.R' 'funs.R' 'glimpse.R' 'group-by.r' 'group-indices.R' 'group-size.r' 'grouped-df.r' 'grouped-dt.r' 'id.r' 'inline.r' 'join.r' 'lead-lag.R' 'location.R' 'manip.r' 'nth-value.R' 'order-by.R' 'over.R' 'partial-eval.r' 'progress.R' 'query.r' 'rank.R' 'rbind.r' 'rowwise.r' 'sample.R' 'select-utils.R' 'select-vars.R' 'sets.r' 'sql-escape.r' 'sql-star.r' 'src-local.r' 'src-mysql.r' 'src-postgres.r' 'src-sql.r' 'src-sqlite.r' 'src.r' 'tally.R' 'tbl-cube.r' 'tbl-df.r' 'tbl-dt.r' 'tbl-sql.r' 'tbl.r' 'top-n.R' 'translate-sql-helpers.r' 'translate-sql-base.r' 'translate-sql-window.r' 'translate-sql.r' 'type-sum.r' 'utils-dt.R' 'utils-format.r' 'utils.r' 'view.r' 'zzz.r'
# NeedsCompilation: yes
# Packaged: 2015-08-31 18:19:11 UTC; hadley
# Author: Hadley Wickham [aut, cre], Romain Francois [aut], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2015-09-01 18:15:02
#----------------------------------------------------------------------
