--- Makefile
+++ Makefile
@@ -235,10 +235,12 @@
 
 both-debug: hisat2-align-s-debug hisat2-align-l-debug hisat2-build-s-debug hisat2-build-l-debug
 
+BUILD_HOST=$(shell echo BioBuilds `uname -sm` | tr 'A-Z ' 'a-z-')
+BUILD_TIME=$(shell date -u '+%Y-%m-%dT%H:%M:%SZ')
 DEFS=-fno-strict-aliasing \
      -DHISAT2_VERSION="\"`cat VERSION`\"" \
-     -DBUILD_HOST="\"`hostname`\"" \
-     -DBUILD_TIME="\"`date`\"" \
+     -DBUILD_HOST="\"$(BUILD_HOST)\"" \
+     -DBUILD_TIME="\"$(BUILD_TIME)\"" \
      -DCOMPILER_VERSION="\"`$(CXX) -v 2>&1 | tail -1`\"" \
      $(FILE_FLAGS) \
      $(PREF_DEF) \
