{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-testthat
  version: "1.0.2"

source:
  fn: testthat_1.0.2.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/testthat_1.0.2.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/testthat/testthat_1.0.2.tar.gz

build:
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

requirements:
  build:
    - r-base
    - r-r6
    - r-crayon
    - r-digest
    - r-magrittr
    - r-praise
    - posix               # [win]
    - {{native}}toolchain # [win]
    - gcc                 # [not win and not ppc64le]

  run:
    - r-base
    - r-r6
    - r-crayon
    - r-digest
    - r-magrittr
    - r-praise
    - libgcc              # [not win and not ppc64le]

test:
  commands:
    - $R -e "library('testthat')" # [not win]
    - "\"%R%\" -e \"library('testthat')\"" # [win]

about:
  home: https://github.com/hadley/testthat
  license: MIT + file LICENSE
  summary: "Unit testing system designed to be flexible and easy to set up."


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:

# Package: testthat
# Version: 1.0.2
# Title: Unit Testing for R
# Description: A unit testing system designed to be fun, flexible and easy to set up.
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", c("aut", "cre")), person("RStudio", role = "cph") )
# URL: https://github.com/hadley/testthat
# BugReports: https://github.com/hadley/testthat/issues
# Depends: R (>= 3.1.0)
# Imports: digest, crayon, praise, magrittr, R6, methods
# Suggests: devtools, withr, covr
# License: MIT + file LICENSE
# Collate: 'auto-test.R' 'colour-text.R' 'compare.R' 'compare-character.R' 'compare-numeric.R' 'compare-time.R' 'context.R' 'describe.R' 'evaluate-promise.R' 'expect-comparison.R' 'expect-equal-to-reference.R' 'expect-equality.R' 'expect-inheritance.R' 'expect-length.R' 'expect-logical.R' 'expect-named.R' 'expect-output.R' 'reporter.R' 'expect-self-test.R' 'expect-that.R' 'expectation.R' 'expectations-matches.R' 'make-expectation.R' 'mock.R' 'old-school.R' 'praise.R' 'reporter-check.R' 'reporter-fail.R' 'reporter-list.R' 'reporter-minimal.R' 'reporter-multi.R' 'reporter-rstudio.R' 'reporter-silent.R' 'reporter-stop.R' 'stack.R' 'reporter-summary.R' 'reporter-tap.R' 'reporter-teamcity.R' 'reporter-zzz.R' 'skip.R' 'source.R' 'test-compiled-code.R' 'test-example.R' 'test-files.R' 'test-package.R' 'test-path.R' 'test-that.R' 'traceback.R' 'try-again.R' 'utils.R' 'watcher.R'
# RoxygenNote: 5.0.1
# NeedsCompilation: yes
# Packaged: 2016-04-22 20:14:31 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2016-04-23 08:37:40
#----------------------------------------------------------------------
