package:
  name: ncurses
  version: 5.9

requirements:
  build:
    - autoconf-update

source:
  fn: ncurses-5.9.tar.gz
  url: http://ftp.gnu.org/pub/gnu/ncurses/ncurses-5.9.tar.gz
  md5: 8cb9c412e5f2d96bc6f459aa8c6282a1
  patches:
    # http://lists.gnu.org/archive/html/bug-ncurses/2011-04/txtkWQqiQvcZe.txt
    - fix.patch

build:
  # Bumping build number to avoid conflicts with "default" and "r" channels
  number: 7
  detect_binary_files_with_prefix: true

about:
  home: http://www.gnu.org/software/ncurses/
  license:  Free software (X11 License)
