package:
  name: bedtools
  version: "2.26.0"

requirements:
  build:
    - zlib
  run:
    - zlib

source:
  fn: bedtools-2.26.0.tar.gz
  url:
    - "https://github.com/arq5x/bedtools2/archive/v2.26.0.tar.gz"
    - "http://download.lab7.io/sources/bedtools-2.26.0.tar.gz"
  md5: "52227e7efa6627f0f95d7d734973233d"
  patches:
    - bedtools-makefile.patch

build:
  number: 0
  script_env:
    - BB_ARCH_FLAGS
    - BB_OPT_FLAGS
    - BB_MAKE_JOBS

about:
  home: http://bedtools.readthedocs.org/
  license: GPLv2
  license_file: LICENSE
  summary: "Swiss-army knife of tools for a wide-range of genomics analysis tasks"
