{% set name = "dplyr" %}
{% set version = "0.7.4" %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-{{ name|lower }}_{{ version }}.tar.gz"
  sha256: "7b1fc90750fbb46483423da6721832c545d37b157f4f3355784a65e50fada8c2"

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base {{ r_base }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - r-bh >=1.58.0_1
    - r-r6
    - r-rcpp >=0.12.7
    - r-assertthat
    - r-bindrcpp >=0.2
    - r-glue >=1.1.1
    - r-magrittr
    - r-pkgconfig
    - r-plogr
    - r-rlang >=0.1.2
    - r-tibble >=1.3.1

  run:
    - r-base
    - r-bh >=1.58.0_1
    - r-r6
    - r-rcpp >=0.12.7
    - r-assertthat
    - r-bindrcpp >=0.2
    - r-glue >=1.1.1
    - r-magrittr
    - r-pkgconfig
    - r-plogr
    - r-rlang >=0.1.2
    - r-tibble >=1.3.1

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: http://dplyr.tidyverse.org, https://github.com/tidyverse/dplyr
  license: MIT
  summary: A grammar for data manipulation
  description: |
    A fast, consistent tool for working with data frame like objects, both in
    memory and out of memory.


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Type: Package
# Package: dplyr
# Version: 0.7.4
# Title: A Grammar of Data Manipulation
# Description: A fast, consistent tool for working with data frame like objects, both in memory and out of memory.
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", c("aut", "cre")), person("Romain", "Francois", , "romain@r-enthusiasts.com", role = "aut"), person("Lionel", "Henry", role = "aut"), person("Kirill", "MAzller", role = "aut"), person("RStudio", role = c("cph", "fnd")) )
# URL: http://dplyr.tidyverse.org, https://github.com/tidyverse/dplyr
# BugReports: https://github.com/tidyverse/dplyr/issues
# Encoding: UTF-8
# Depends: R (>= 3.1.2)
# Imports: assertthat, bindrcpp (>= 0.2), glue (>= 1.1.1), magrittr, methods, pkgconfig, rlang (>= 0.1.2), R6, Rcpp (>= 0.12.7), tibble (>= 1.3.1), utils
# Suggests: bit64, covr, dbplyr, dtplyr, DBI, ggplot2, hms, knitr, Lahman (>= 3.0-1), mgcv, microbenchmark, nycflights13, rmarkdown, RMySQL, RPostgreSQL, RSQLite, testthat, withr
# VignetteBuilder: knitr
# LinkingTo: Rcpp (>= 0.12.0), BH (>= 1.58.0-1), bindrcpp, plogr
# LazyData: yes
# License: MIT + file LICENSE
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-09-16 15:25:52 UTC; muelleki
# Author: Hadley Wickham [aut, cre], Romain Francois [aut], Lionel Henry [aut], Kirill MAzller [aut], RStudio [cph, fnd]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-09-28 20:43:29 UTC
#----------------------------------------------------------------------
