{% set name = "magrittr" %}
{% set version = "1.5" %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-{{ name|lower }}_{{ version }}.tar.gz"
  sha256: "05c45943ada9443134caa0ab24db4a962b629f00b755ccf039a2a2a7b2c92ae8"

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base {{ r_base }}

  run:
    - r-base

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: 'https://cran.r-project.org/web/packages/magrittr/index.html'
  license: MIT
  license_file: LICENSE
  summary: 'A forward-pipe operator ("%>%") for R'
  description: |
    Provides a mechanism for chaining commands with a new forward-pipe
    operator, %>%. This operator will forward a value, or the result of an
    expression, into the next function call/expression. There is flexible
    support for the type of right-hand side expressions. For more information,
    see package vignette. To quote Rene Magritte, "Ceci n'est pas un pipe."


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:

# Package: magrittr
# Type: Package
# Title: A Forward-Pipe Operator for R
# Version: 1.5
# Author: Stefan Milton Bache <stefan@stefanbache.dk> and Hadley Wickham <h.wickham@gmail.com>
# Maintainer: Stefan Milton Bache <stefan@stefanbache.dk>
# Description: Provides a mechanism for chaining commands with a new forward-pipe operator, %>%. This operator will forward a value, or the result of an expression, into the next function call/expression. There is flexible support for the type of right-hand side expressions. For more information, see package vignette. To quote Rene Magritte, "Ceci n'est pas un pipe."
# Suggests: testthat, knitr
# VignetteBuilder: knitr
# License: MIT + file LICENSE
# ByteCompile: Yes
# Packaged: 2014-11-22 08:50:53 UTC; shb
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-11-22 19:15:57
#----------------------------------------------------------------------
