{% set version = "7.0" %}

package:
  name: readline
  version: "{{ version }}"

source:
  fn: "readline-{{ version }}.tar.gz"
  url: 
    - "ftp://ftp.gnu.org/gnu/readline/readline-{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/readline-{{ version }}.tar.gz"
  sha256: "750d437185286f40a369e1e4f4764eda932b9459b5ec9a731628393dd3d32334"
  patches:
    - patches/readline70-001
    - patches/readline70-002
    - patches/readline70-003

build:
  skip: true  # [win]
  number: 0
  run_exports:
    # change soname at major ver: https://abi-laboratory.pro/tracker/timeline/readline/
    - {{ pin_subpackage('readline') }}

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
  host:
    - ncurses {{ ncurses }}

test:
  commands:
  {% set readline_libs = [
    'libreadline',
    'libhistory'
  ] %}
  {% for lib in readline_libs %}
    - test -f ${PREFIX}/lib/{{ lib }}.a
    - test -f ${PREFIX}/lib/{{ lib }}.so      # [linux]
    - test -f ${PREFIX}/lib/{{ lib }}.dylib   # [osx]
  {% endfor %}

about:
  home: https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
  license: GPL3
  license_file: COPYING
  summary: library for editing command lines as they are typed in
  description: |
    The standard Python readline extension statically linked against the GNU
    readline library.
  doc_url: https://pypi.python.org/pypi/readline
  dev_url: https://github.com/ludwigschwardt/python-gnureadline
  doc_source_url: https://github.com/ludwigschwardt/python-gnureadline

extra:
  recipe-maintainers:
    - croth1
    - jakirkham
    - jjhelmus
    - pelson
    - msarahan
    - asmeurer
    - mingwandroid
    - chenghlee
