{% set name = 'rio' %}
{% set version = '0.5.5' %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-{{ name|lower }}_{{ version }}.tar.gz"
  sha256: "c3d5df013f666e32e81aeaacbf0f7d4d7a00232d363d703ca411bafd05a602f2"

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base {{ r_base }}
    - r-curl >=0.6
    - r-data.table >=1.9.8
    - r-foreign
    - r-haven >0.2.1
    - r-openxlsx
    - r-readxl >=0.1.1
    - r-tibble

  run:
    - r-base
    - r-curl >=0.6
    - r-data.table >=1.9.8
    - r-foreign
    - r-haven >0.2.1
    - r-openxlsx
    - r-readxl >=0.1.1
    - r-tibble

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: https://github.com/leeper/rio
  license: GPLv2
  summary: A swiss-army knife for data I/O
  description: |
    Streamlined data import and export by making assumptions that the user is
    probably willing to make: 'import()' and 'export()' determine the data
    structure from the file extension, reasonable defaults are used for data
    import and export (e.g., 'stringsAsFactors=FALSE'), web-based import is
    natively supported (including from SSL/HTTPS), compressed files can be read
    directly without explicit decompression, and fast import packages are used
    where appropriate. An additional convenience function, 'convert()',
    provides a simple method for converting between file types.


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Package: rio
# Type: Package
# Title: A Swiss-Army Knife for Data I/O
# Version: 0.5.5
# Date: 2017-06-17
# Authors@R: c(person("Jason", "Becker", role = "ctb", email = "jason@jbecker.co"), person("Chung-hong", "Chan", role = "aut", email = "chainsawtiney@gmail.com"), person("Geoffrey CH", "Chan", role = "ctb", email = "gefchchan@gmail.com"), person("Thomas J.", "Leeper", role = c("aut", "cre"), email = "thosjleeper@gmail.com"), person("Christopher", "Gandrud", role = "ctb"), person("Andrew", "MacDonald", role = "ctb"), person("Ista", "Zahn", role = "ctb"), person("Stanislaus", "Stadlmann", role = "ctb"))
# Description: Streamlined data import and export by making assumptions that the user is probably willing to make: 'import()' and 'export()' determine the data structure from the file extension, reasonable defaults are used for data import and export (e.g., 'stringsAsFactors=FALSE'), web-based import is natively supported (including from SSL/HTTPS), compressed files can be read directly without explicit decompression, and fast import packages are used where appropriate. An additional convenience function, 'convert()', provides a simple method for converting between file types.
# URL: https://github.com/leeper/rio
# BugReports: https://github.com/leeper/rio/issues
# Depends: R (>= 2.15.0)
# Imports: tools, stats, utils, foreign, haven (> 0.2.1), curl (>= 0.6), data.table (>= 1.9.8), readxl (>= 0.1.1), openxlsx, tibble
# Suggests: datasets, bit64, testthat, knitr, magrittr, clipr, csvy, feather, fst, jsonlite, readODS (>= 1.6.4), readr, rmatio, xml2 (>= 1.0.0), yaml
# License: GPL-2
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-06-17 20:02:16 UTC; THOMAS
# Author: Jason Becker [ctb], Chung-hong Chan [aut], Geoffrey CH Chan [ctb], Thomas J. Leeper [aut, cre], Christopher Gandrud [ctb], Andrew MacDonald [ctb], Ista Zahn [ctb], Stanislaus Stadlmann [ctb]
# Maintainer: Thomas J. Leeper <thosjleeper@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-06-18 13:20:01 UTC
#----------------------------------------------------------------------
