{% set name = "GenomeInfoDbData" %}
{% set version = "0.99.1" %}
{% set bioc_version = "3.6" %}

package:
  name: "bioconductor-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "bioconductor-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "https://bioconductor.org/packages/{{ bioc_version }}/data/annotation/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-{{ name|lower }}_{{ version }}.tar.gz"
  # NOTE: For reasons we don't fully understand, this is not the same tarball
  # you get by running curl/wget on the first URL above.
  sha256: "39809792f2c88939ed3ea4ecfee1cbdfb1d575194f6a888c2d07e6edf78d3742"

requirements:
  build:
    - r-base {{ r_base }}
  run:
    - r-base

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

test:
  commands:
    - $R -e "library('{{ name }}')"           # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\""  # [win]

about:
  home: "https://bioconductor.org/packages/release/bioc/html/{{ name }}.html"
  license: Artistic 2.0
  summary: Species and taxonomy ID look up tables used by GenomeInfoDb
  description: |
    Files for mapping between NCBI taxonomy ID and species. Used by functions
    in the GenomeInfoDb package.
