{% set name = "gettext" %}
{% set version = "0.19.8.1" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  fn: "{{ name }}-{{ version }}.tar.xz"
  url:
    - "ftp://ftp.gnu.org/pub/gnu/{{ name }}/{{ name }}-{{ version }}.tar.xz"
    - "http://download.lab7.io/sources/{{ name }}-{{ version }}.tar.xz"
  sha256: "105556dbc5c3fbbc2aa0edb46d22d055748b6f5c7cd7a8d99f8e7eb84e938be4"

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - libffi
    - libiconv  # [not linux and not win]

test:
  commands:
    - test -f ${PREFIX}/lib/libgettextlib.so  # [linux]
    - test -f ${PREFIX}/lib/libintl.dylib     # [osx]

about:
  home: https://www.gnu.org/software/gettext/
  license: GPLv2
  license_file: COPYING
  summary: "Internationalization package."

extra:
  recipe-maintainers:
    - scopatz
    - chenghlee
