{% set version = "1.6.34" %}

package:
  name: libpng
  version: "{{ version }}"

source:
  fn: "libpng-{{ version }}.tar.gz"
  url:
    - "http://download.sourceforge.net/libpng/libpng-{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/libpng-{{ version }}.tar.gz"
  sha256: "574623a4901a9969080ab4a2df9437026c8a87150dfd5c235e28c94b212964a7"

build:
  number: 0
  run_exports:
    # SO name changes at minor rev bumps.
    - {{ pin_subpackage('libpng', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
    - automake
  host:
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/libpng.a
    - test -f ${PREFIX}/lib/libpng.so           # [linux]
    - test -f ${PREFIX}/lib/libpng.dylib        # [osx]
    - libpng-config --version
    - conda inspect linkages -p $PREFIX libpng
    - conda inspect objects -p $PREFIX libpng   # [osx]

about:
  home: http://www.libpng.org/pub/png/libpng.html
  license: zlib/libpng
  license_file: LICENSE
  license_url: http://www.libpng.org/pub/png/src/libpng-LICENSE.txt
  summary: 'PNG reference library.'
  description: |
    libpng is the official PNG reference library. It supports almost all PNG
    features, is extensible, and has been extensively tested for over 20 years.
  doc_url: http://www.libpng.org/pub/png/libpng.html
  dev_url: https://sourceforge.net/p/libpng/code/ci/libpng16/tree/

extra:
  recipe-maintainers:
    - ocefpaf
    - msarahan
    - chenghlee
